---
- name: insall packages
  yum:
    name: ['dnsmasq', 'vsftpd']
    state: present
    update_cache: yes

- name: create folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ tftp_root }}/bionic"
    - "{{ ftp_root }}/bionic"

- name: mount iso image
  mount:
    path: "{{ ftp_root }}/bionic"
    src: "{{ cdrom }}"
    fstype: iso9660
    state: mounted

- name: copy boot modules
  copy:
    src: "{{ ftp_root }}/bionic/install/netboot/"
    dest: "{{ tftp_root }}"

- name: copy boot images
  copy:
    src: "{{ item }}"
    dest: "{{ tftp_root }}/bionic"
  with_items:
    - "{{ ftp_root }}/bionic/install/vmlinuz"
    - "{{ ftp_root }}/bionic/install/initrd.gz"

- name: generate dnsmasq config
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify:
    - restart dnsmasq

- name: generate unattended install
  template:
    src: preseed.cfg.j2
    dest: "{{ ftp_root }}/preseed.cfg"
  notify:
    - restart ftp

- name: generate txt.cfg
  template:
    src: txt.cfg.j2
    dest: "{{ tftp_root }}/ubuntu-installer/amd64/boot-screens/txt.cfg"
  notify:
    - restart dnsmasq

- name: generate rqtxt.cfg
  template:
    src: rqtxt.cfg.j2
    dest: "{{ tftp_root }}/ubuntu-installer/amd64/boot-screens/rqtxt.cfg"
  notify:
    - restart dnsmasq

- name: generate default menu
  template:
    src: default.j2
    dest: "{{ tftp_root }}/pxelinux.cfg/default"
  notify:
    - restart dnsmasq

- name: ensure services are started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: 
    - dnsmasq
    - vsftpd

- name: allow services in firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - dhcp
    - ftp

- name: allow ports in firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 69/udp
    - 4011/udp

- name: disable seliunx
  selinux:
    state: disabled
